### PR TITLE
Implement pre-commit along with Mypy and Ruff

### PR DESCRIPTION
**Pull request by albertoursino**
Run `poetry install` to update your Python environment by installing [pre-commit](https://pre-commit.com/#intro), and run `pre-commit install` to install pre-commit hooks ([Mypy](https://github.com/pre-commit/mirrors-mypy) and [Ruff](https://github.com/astral-sh/ruff-pre-commit)).

Before every commit, from now on after this PR: 

- **Mypy** will check all type hints and their coherence;
- **Ruff** will check that the code is well formatted, and will _automatically_ format parts of code whenever it is secure to format without supervision. Ruff is configurable in `pyproject.toml`.

If the checks fail you are not able to commit until you fix the errors.

### CODE REVIEW

**Review by Fabio-Marangoni — DISMISSED** [review]

**Review by d-u-d-e — APPROVED** [review]
Pretty cool I must say

**Comment by CremaLuca** [comment]
Could one set up pre-commit hooks while running poetry install? Let me check the internet these two things could be chained together

**Comment by CremaLuca** [comment]
Moved to label `chore` as it is not a functionality addition but a developer-only one

**Comment by albertoursino** [comment]
> Could one set up pre-commit hooks while running poetry install? Let me check the internet these two things could be chained together

https://pypi.org/project/poetry-pre-commit-plugin/

**Comment by CremaLuca** [comment]
Could you also update the `README.md` by adding a `Development` section where you list the needed command(s) to start developing which currently are `poetry install --with dev` and `pre-commit install`?

**Comment by albertoursino** [comment]
> poetry install --with dev

Actually `--with dev` is not necessary since the group is not optional. 

If one doesn't want to install dev deps they should run `poetry install --without dev`

**Review by d-u-d-e — APPROVED** [review]

**Review by CremaLuca — APPROVED** [review]

**Review by CremaLuca — APPROVED** [review]

**Review by d-u-d-e — DISMISSED** [review]

**Review by CremaLuca — APPROVED** [review]

**Review by d-u-d-e — APPROVED** [review]

**Pull request merged**
