### PR TITLE
Chapter 1: A Minimal Compiler

### PR DESCRIPTION
**Pull request by albertoursino**

### CODE REVIEW

**Review by d-u-d-e — COMMENTED** [review]
Should we add the `__init__.py` files inside `assembly_generation` and `code_emission` for coherence?

**Comment by albertoursino** [comment]
> Should we add the `__init__.py` files inside `assembly_generation` and `code_emission` for coherence?

Do we actually need them? I tried to remove them and everything work.

**Comment by Fabio-Marangoni** [comment]
> Should we add the `__init__.py` files inside `assembly_generation` and `code_emission` for coherence?

For what I understood, the whole code works fine without those `__init__.py` files as long as we keep running it with Poetry (thanks to the specifications inside .toml file). Personally I would add them, allowing to prescind from the execution through Poetry's environment.

**Comment by albertoursino** [comment]
In order to release something we have to create a branch “release” from develop and then create a PR from it.

New PR: https://github.com/d-u-d-e/c-compiler/pull/31

**Pull request merged**
